app/src/myproject/myapp/urls.py
from django.urls import path

from . import views

app_name = 'myapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('details', views.details, name='details'),
]

app/src/myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('myapp.urls')),
    path('admin/', admin.site.urls),
]

app/src/myproject/myapp/models.py
from django.db import models


class City(models.Model):
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title


class Mark(models.Model):
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title


class Advertisement(models.Model):
    title = models.CharField(max_length=100)
    image = models.URLField(max_length=255)
    year = models.IntegerField(default=0)
    price = models.IntegerField(default=0)
    description = models.TextField()
    mark = models.ForeignKey(Mark, on_delete=models.CASCADE)
    city = models.ForeignKey(City, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.id}. {self.title} {self.price}"

app/src/myproject/myapp/views.py
from django.shortcuts import render

from .models import Advertisement, City, Mark


def index(request):
    city_id = request.GET.get('city', None)
    mark_id = request.GET.get('mark', None)

    marks = Mark.objects.all()
    cities = City.objects.all()

    advertisements = Advertisement.objects.all()
    if city_id:
        advertisements = advertisements.filter(city=city_id)
    if mark_id:
        advertisements = advertisements.filter(mark=mark_id)

    return render(request, 'myapp/index.html', {
        'marks': marks,
        'cities': cities,
        'advertisements': advertisements,
    })


def details(request):
    return render(request, 'myapp/details.html')

app/src/myproject/myapp/templates/myapp/details.html
{% extends 'base.html' %}

{% block content %}
<h1>Details</h1>
{% endblock %}

app/src/myproject/myapp/templates/myapp/index.html
{% extends 'base.html' %}

{% block content %}
<h1>Index</h1>

<div class="row">
    <div class="col-9">
        <table class="table table-sm">
            <thead>
            <tr>
                <th></th>
                <th>სათაური</th>
                <th>ფასი</th>
                <th>წელი</th>
                <th>ქალაქი</th>
                <th>მარკა</th>
            </tr>
            </thead>
            <tbody>
            {% for adv in advertisements %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>
                    <div>{{ adv.title }}</div>
                    <div>
                        <img src="{{adv.image }}" style="max-width: 100px; max-height: 100px;">
                    </div>
                </td>
                <td>{{ adv.price }}</td>
                <td>{{ adv.year }}</td>
                <td>{{ adv.city }}</td>
                <td>{{ adv.mark }}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="col-3">
        <form action="" method="get">
            <label>მარკა</label>
            <select name="mark" class="form-control">
                <option value=""></option>
                {% for mark in marks %}
                    {% if request.GET.mark == mark.id|stringformat:'i' %}
                    <option value="{{ mark.id }}" selected>{{ mark.title }}</option>
                    {% else %}
                    <option value="{{ mark.id }}">{{ mark.title }}</option>
                    {% endif %}
                {% endfor %}
            </select>
            <label class="mt-3">ქალაქი</label>
            <select name="city" class="form-control">
                <option value=""></option>
                {% for city in cities %}
                    {% if request.GET.city == city.id|stringformat:'i' %}
                    <option value="{{ city.id }}" selected>{{ city.title }}</option>
                    {% else %}
                    <option value="{{ city.id }}">{{ city.title }}</option>
                    {% endif %}
                {% endfor %}
            </select>
            <div class="input-group mt-3">
                <button type="submit" class="btn btn-primary btn-sm">მოძებნა</button>
                <a href="{% url 'myapp:index' %}" class="btn btn-secondary btn-sm ml-4">წაშლა</a>
            </div>
        </form>
    </div>
</div>

{% endblock %}